# Generated by Django 5.1.2 on 2024-10-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_by',
        ),
    ]
