# Generated by Django 5.1.2 on 2024-10-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_created_by_remove_product_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_by',
        ),
    ]
